#!/bin/bash
# 文件整理脚本 - 请手动逐条执行

echo "====================================="
echo "文件整理命令（请手动执行）"
echo "====================================="

echo ""
echo "1. 归档回归树相关文件（9棵树方案）"
echo "mv battle_regression_tree.py archive/regression_tree_approach/"
echo "mv train/viper_regression.py archive/regression_tree_approach/"
echo "mv REGRESSION_TREE_GUIDE.md archive/regression_tree_approach/"
echo "mv REGRESSION_TREE_README.md archive/regression_tree_approach/"

echo ""
echo "2. 归档旧文档"
echo "mv EXECUTE_NOW.md archive/old_docs/"
echo "mv FINAL_FIX_COMMANDS.md archive/old_docs/"
echo "mv FIX_SUMMARY.md archive/old_docs/"
echo "mv IMPLEMENTATION_SUMMARY.md archive/old_docs/"
echo "mv LEARNINGS.md archive/old_docs/"
echo "mv QUICK_COMMANDS.md archive/old_docs/"
echo "mv QUICK_START_RULE_EXTRACTION.md archive/old_docs/"
echo "mv SOLUTION_README.md archive/old_docs/"
echo "mv TRAINING_GUIDE.md archive/old_docs/"
echo "mv URGENT_FIX.md archive/old_docs/"

echo ""
echo "3. 归档调试脚本"
echo "mv debug_illegal_moves.py archive/old_scripts/"
echo "mv debug_tree.py archive/old_scripts/"
echo "mv debug_viper_data.py archive/old_scripts/"
echo "mv diagnose_tree.py archive/old_scripts/"
echo "mv fix_battle_perspective.py archive/old_scripts/"
echo "mv test_minmax_openings.py archive/old_scripts/"
echo "mv test_nn_predictions.py archive/old_scripts/"
echo "mv test_tree_perspective.py archive/old_scripts/"
echo "mv train_viper_improved.py archive/old_scripts/"

echo ""
echo "4. 归档旧shell脚本"
echo "mv run_improved_viper.sh archive/old_scripts/"
echo "mv run_viper.sh archive/old_scripts/"
echo "mv train_with_minmax.sh archive/old_scripts/"
echo "mv verify_installation.sh archive/old_scripts/"

echo ""
echo "5. 整合规则提取脚本（保留最好的）"
echo "# 保留 extract_tree_rules.py"
echo "mv demo_rule_extraction.py archive/old_scripts/"
echo "mv summarize_rules.py archive/old_scripts/"

echo ""
echo "====================================="
echo "完成后项目结构将更清晰！"
echo "====================================="
